 export const progressData=[
  {
    "id":1,
    "skillName":"html",
    "progressValue":"70"
  },
  {
    "id":2,
    "skillName":"css",
    "progressValue":"80"
  },
  {
    "id":3,
    "skillName":"javascript",
    "progressValue":"90"
  },
  {
    "id":4,
    "skillName":"bootstrap",
    "progressValue":"80"
  },
  {
    "id":5,
    "skillName":"ReactJs",
    "progressValue":"87"
  },
  {
    "id":6,
    "skillName":"angular",
    "progressValue":"50"
  },
  {
    "id":7,
    "skillName":"jquery",
    "progressValue":"40"
  }
     
 ]